<?php

namespace app\modules\admin;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->errorHandler->errorAction = 'admin/main/error';
    }
}